[package]
name = "github_build_test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.4"
#relm4 = "0.4.4"
#relm4-components = "0.4.4"
