name: Release_x86

on:
  push:
    branches: [ main ]
    tags:
      - "v*.*.*"
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  release-for-x86:
    runs-on: ubuntu-latest
    name: ci (amd64)
    container:
      image: ubuntu:jammy
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install dependencies
        run:  |
            apt-get update -q -y
            apt-get upgrade -y
            apt-get install -q -y binutils rust-all libgtk-4-dev libadwaita-1-dev
      - name: Build and test debug binary
        run: |
            cargo build --verbose
            cargo test --verbose
            mv target/debug/github_build_test target/debug/github_build_test_debug_x86_64
      - name: Build, test and strip the release binary
        if: startsWith(github.ref, 'refs/tags/')
        run: |
            cargo build --release --verbose
            cargo test --release --verbose
            strip --strip-all target/release/github_build_test
            mv target/release/github_build_test target/release/github_build_test_x86_64
      - name: Add debug binary to release
        uses: svenstaro/upload-release-action@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/debug/github_build_test_debug_x86_64
          tag: ${{ github.ref }}
          overwrite: true
      - name: Add release binary to release
        uses: svenstaro/upload-release-action@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/release/github_build_test_x86_64
          tag: ${{ github.ref }}
          overwrite: true