name: release_pkgbuild

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  release-pkgbuild:
    runs-on: ubuntu-latest
    steps:
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/v}
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Replace the version number
        run: |
            sed -i 's/PACKAGEVERSION/${{ steps.get_version.outputs.VERSION }}/g' PKGBUILD


      - name: Upload PKGBUILD to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: PKGBUILD
          tag: ${{ github.ref }}
          overwrite: true