name: Release_aarch64

on:
  push:
    branches: [ main ]
    tags:
      - "v*.*.*"
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  release-for-aarch64:
    runs-on: ubuntu-latest
    name: ci (arm64)
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Build in arm64 container
        uses: uraimo/run-on-arch-action@v2.5.0
        with:
          arch: aarch64
          distro: ubuntu_devel
          # Install deps into the container. With the token, the container will be cached
          # The image is cached publically like a package
          githubToken: ${{ github.token }}
          #  Install packages for the arm container (e.g. Dockerfile steps)
          install: |
            apt-get update -q -y
            apt-get upgrade -y
            apt-get install -q -y binutils rust-all libgtk-4-dev libadwaita-1-dev
          #   .. run build steps on the container
          run: |
            uname -m
            cat /etc/lsb-release
            cargo build --verbose
            cargo test --verbose
            mv target/debug/github_build_test target/debug/github_build_test_debug_aarch64
            cargo build --release --verbose
            cargo test --release --verbose
            strip --strip-all target/release/github_build_test
            mv target/release/github_build_test target/release/github_build_test_aarch64
      - name: Upload debug binary to release
        uses: svenstaro/upload-release-action@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/debug/github_build_test_debug_aarch64
          tag: ${{ github.ref }}
          overwrite: true
      - name: Upload release binary to release
        uses: svenstaro/upload-release-action@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/release/github_build_test_aarch64
          tag: ${{ github.ref }}
          overwrite: true