name: Release_x86

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  release-for-x86:
    runs-on: ubuntu-latest
    name: ci (amd64)
    steps:
      - name: Checkout code
        uses: actions/checkout@v2








      - name: Install dependencies
        run:  |
            sudo apt-get update -q -y
            sudo apt-get upgrade -y
            sudo apt-get install -q -y rust-all libgtk-4-dev libadwaita-1-dev
      - name: Build
        run: cargo build --release --verbose
      - name: Run tests
        run: cargo test --release --verbose